# frozen_string_literal: true

source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'assert'
gem 'cucumber'
gem 'nokogiri'
gem 'page-object'
gem 'rake'
gem 'waitutil'
gem 'watir'
